presets:
  link:
    default:
      latency: 1000ns
      throughput: 10Gbps
      ingress_buffer_size: 64KB
      egress_buffer_size: 64KB

packet-spraying:
  type: ecmp

hosts:
  sender:
  receiver:

switches:
  switch:

links:
  link-1:
    from: sender
    to: switch
    preset-name: default
  link-2:
    from: switch
    to: sender
    preset-name: default
  link-3:
    from: switch
    to: receiver
    preset-name: default
  link-4:
    from: receiver
    to: switch
    preset-name: default
