topology_config_path: topology.yml

presets:
  default-flow:
    type: tcp
    metrics_filters:
      rtt: false
      reordering: false
      delivery_rate: false

type: all-to-all

connections_params:
  type: mplb-connection
  mplb:
    type: single-cc
    packet-size: 1500B

    metrics_filters:
      fairness: false

    cc:
      type: swift
      base_target: 20000ns
      metrics_filters:
        cwnd: false

    path-chooser:
      type: round-robin
      flows:
        flow-1:
          type: tcp
          preset-name: default-flow

        flow-2:
          type: tcp
          preset-name: default-flow

        flow-3:
          type: tcp
          preset-name: default-flow
