topology_config_path: topology.yml
type: all-to-all

connections_params:
  type: mplb-connection
  mplb:
    type: single-cc
    packet-size: 1500B
    cc:
      type: tahoe
    path-chooser:
      type: round-robin
      flows:
        flow:
          type: tcp

