type: custom
topology_config_path: topology.yml

presets:
  default-connection:
    type: mplb-connection
    mplb:
      type: single-cc
      packet-size: 1500B
      cc:
        type: swift
        base_target: 12500ns
      path-chooser:
        type: round-robin
        flows:
          flow-1:
            type: tcp
          flow-2:
            type: tcp
          flow-3:
            type: tcp
          flow-4:
            type: tcp
          flow-5:
            type: tcp

connections:
  conn:
    preset-name: default-connection
    sender_id: host-1
    receiver_id: host-4
