topology_config_path: topology.yml

presets:
  connection:
    default:
      type: mplb-connection
      mplb:
        type: single-cc
        packet-size: 1500B
        cc:
          type: tahoe
        path-chooser:
          type: round-robin
          flows:
            flow:
              type: tcp

connections:
  conn_1->2:
    sender_id: host_1
    receiver_id: host_2
    preset-name: default
  conn_1->3:
    sender_id: host_1
    receiver_id: host_3
    preset-name: default
  conn_1->4:
    sender_id: host_1
    receiver_id: host_4
    preset-name: default
  conn_2->1:
    sender_id: host_2
    receiver_id: host_1
    preset-name: default
  conn_2->3:
    sender_id: host_2
    receiver_id: host_3
    preset-name: default
  conn_2->4:
    sender_id: host_2
    receiver_id: host_4
    preset-name: default
  conn_3->1:
    sender_id: host_3
    receiver_id: host_1
    preset-name: default
  conn_3->2:
    sender_id: host_3
    receiver_id: host_2
    preset-name: default
  conn_3->4:
    sender_id: host_3
    receiver_id: host_4
    preset-name: default
  conn_4->1:
    sender_id: host_4
    receiver_id: host_1
    preset-name: default
  conn_4->2:
    sender_id: host_4
    receiver_id: host_2
    preset-name: default
  conn_4->3:
    sender_id: host_4
    receiver_id: host_3
    preset-name: default
