type: custom
presets:
  default-link:
    latency: 0ns
    throughput: 100Gbps
    ingress_buffer_size: 64KB
    egress_buffer_size: 64KB
    metrics_filters:
      queue_sizes: false

packet-spraying:
  type: random

hosts:
  host_1:
  host_2:
  host_3:
  host_4:

switches:
  spine_1:
  spine_2:
  leaf_1:
  leaf_2:
  leaf_3:
  leaf_4:

links:
  # spine_1 links
  spine_1--leaf_1:
    from: spine_1
    to: leaf_1
    preset-name: default-link
  leaf_1--spine_1:
    from: leaf_1
    to: spine_1
    preset-name: default-link
  spine_1--leaf_2:
    from: spine_1
    to: leaf_2
    preset-name: default-link
  leaf_2--spine_1:
    from: leaf_2
    to: spine_1
    preset-name: default-link
  spine_1--leaf_3:
    from: spine_1
    to: leaf_3
    preset-name: default-link
  leaf_3--spine_1:
    from: leaf_3
    to: spine_1
    preset-name: default-link
  spine_1--leaf_4:
    from: spine_1
    to: leaf_4
    preset-name: default-link
  leaf_4--spine_1:
    from: leaf_4
    to: spine_1
    preset-name: default-link

  # spine_2 links
  spine_2--leaf_1:
    from: spine_2
    to: leaf_1
    preset-name: default-link
  leaf_1--spine_2:
    from: leaf_1
    to: spine_2
    preset-name: default-link
  spine_2--leaf_2:
    from: spine_2
    to: leaf_2
    preset-name: default-link
  leaf_2--spine_2:
    from: leaf_2
    to: spine_2
    preset-name: default-link
  spine_2--leaf_3:
    from: spine_2
    to: leaf_3
    preset-name: default-link
  leaf_3--spine_2:
    from: leaf_3
    to: spine_2
    preset-name: default-link
  spine_2--leaf_4:
    from: spine_2
    to: leaf_4
    preset-name: default-link
  leaf_4--spine_2:
    from: leaf_4
    to: spine_2
    preset-name: default-link

  leaf_1--host_1:
    from: leaf_1
    to: host_1
    preset-name: default-link
  host_1--leaf_1:
    from: host_1
    to: leaf_1
    preset-name: default-link

  leaf_2--host_2:
    from: leaf_2
    to: host_2
    preset-name: default-link
  host_2--leaf_2:
    from: host_2
    to: leaf_2
    preset-name: default-link

  leaf_3--host_3:
    from: leaf_3
    to: host_3
    preset-name: default-link
  host_3--leaf_3:
    from: host_3
    to: leaf_3
    preset-name: default-link

  leaf_4--host_4:
    from: leaf_4
    to: host_4
    preset-name: default-link
  host_4--leaf_4:
    from: host_4
    to: leaf_4
    preset-name: default-link
