import argparse
import os
import tempfile
import subprocess
import sys

def process_simulation_generator(nons_path : str, simulation_generator_dir_path : str) -> bool:
    """"
    Checks given simulation generator:
    1) Generate simulation using generator
    2) Runs nons on it
    Returns true if check succeed, false otherwise
    """
    python_generator_path = None
    default_config_path = None
    for item in sorted(os.listdir(simulation_generator_dir_path)):
        item_path = os.path.join(simulation_generator_dir_path, item)
        if os.path.isdir(item_path):
            continue
        if item.endswith(".py") and item != "__init__.py":
            if python_generator_path is None:
                print(f"Found python generator {item} in directory {simulation_generator_dir_path}")
                python_generator_path = item_path
            else:
                print(f"Found one more python script {item} in directory {simulation_generator_dir_path}; ignored")
        elif item.endswith('.yml') or item.endswith('.yaml'):
            if default_config_path is None:
                print(f"Found default config {item} in directory {simulation_generator_dir_path}")
                default_config_path = item_path
            else:
                print(f"Found one more yaml config {item} in directory {simulation_generator_dir_path}; ignored")
    if (python_generator_path is None):
        print(f"Can not find python script in {simulation_generator_dir_path}; ignored")
        return True
    if (default_config_path is None):
        print(f"Error: can not find default config in {simulation_generator_dir_path}", file=sys.stderr)
        return False
    
    with tempfile.NamedTemporaryFile(delete=True) as temp_file:
        generator_args = [
            "python3",
            python_generator_path,
            "-c",
            default_config_path,
            "-o",
            temp_file.name
        ]
        result = subprocess.run(generator_args, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Command {generator_args} failed; stderr:", file=sys.stderr)
            print(result.stderr, file=sys.stderr)
            return False
        print(result.stdout)
        with tempfile.TemporaryDirectory() as temp_dir:
            nons_args = [
                nons_path,
                "-c",
                temp_file.name,
                "--metrics-filter=", # run without metrics collection
                f"--output-dir={temp_dir}"
            ]
            result = subprocess.run(nons_args, capture_output=True, text=True)
            if result.returncode != 0:
                print(f"Simulation with config generated by {python_generator_path} failed", file=sys.stderr)
                print("Config content:", file=sys.stderr)
                with open(temp_file.name, "r") as f:
                    print(f.read(), file=sys.stderr)
                print("=" * 30, file=sys.stderr)
                print("Nons stderr:", file=sys.stderr)
                print(result.stderr, file=sys.stderr)
                print("=" * 50, file=sys.stderr)
                return False
            print(f"Simulation with config generated by {python_generator_path} succeed!")
            return True

def process_simulation_generators(nons_path : str, simulation_generators_dir : str) -> bool:
    """
    Checks all simulation generators in given direcrory
    Returns true if all checks succeed, false otherwise
    """
    result = True
    for item in sorted(os.listdir(simulation_generators_dir)):
        item_path = os.path.join(simulation_generators_dir, item)
        if not os.path.isdir(item_path):
            continue
        result &= process_simulation_generator(nons_path, item_path)
    return result

def process_topology_generator(
        nons_path : str,
        topology_generator_dir : str,
        universal_simulation_generator : str):
    """
    Checks given topology generator:
    1) Generates topology using script from topology_generator_dir
    2) Generates simulation using universal_simulation_generator
    3) Runs nons on given simulation
    Returns true if check succeed, false otherwise
    """
    pass


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-e", "--executable", help="Path to the compiled project", required=True
    )
    parser.add_argument(
        "-g",
        "--generators",
        help="Path to the directory with generators",
        required=True,
    )
    args = parser.parse_args()

    nons_path = args.executable
    generators_path = args.generators

    simulation_generators_dir = os.path.join(generators_path, "simulation")

    result = True
    result &= process_simulation_generators(nons_path, simulation_generators_dir)

    if not result:
        print("Some checks failed, see stderr for more information", file=sys.stderr)
        exit(-1)
    else:
        print("All checks succeed!")

if __name__ == "__main__":
    main()