name: Check links in markdown files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  check-md-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check md files in root directory
      run: python3 scripts/check-md-files.py -d . -i external