name: CMake Ubuntu latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  create-artefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create artefact
        run: echo "Hello, World!" > hello.txt
      - name: Deploy artefact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

  upload-artefacts:
    runs-on: ubuntu-latest
    needs: create-artefacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: Print artefact
        run: cat hello.txt


  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Clang Format
      run: sudo apt-get install clang-format

    - name: Collect files for Clang
      run:
        files_for_clang="
        main.cpp
        $(
          find source -type f -name "*.cpp" -o -name "*.hpp";
          find test -type f -name "*.cpp" -o -name "*.hpp"
        )"
    - name: Clang format
      run:
        clang-format --dry-run -Werror $files_for_clang
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install gnuplot
      run: sudo apt install gnuplot

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake for building project
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PROJECT=ON -DBUILD_TESTS=OFF

    - name: Build project
      run: cmake --build build --config Debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build/simulator

  run-simulations:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact

    - name: Make Simulator executable
      run: chmod +x simulator

    - name: Run simulation
      run: python3 run_simulations.py simulator configuration_examples/simulation_examples metrics

    - name: Upload metrics
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: metrics/**

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake for building tests
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PROJECT=OFF -DBUILD_TESTS=ON

    - name: Build tests
      run: cmake --build build --config Debug

    - name: Run tests
      working-directory: build
      run: ./test_simulator

