name: Load testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  load_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake for building project
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PROJECT=ON -DBUILD_TESTS=OFF

    - name: Build project
      run: cmake --build build --config Debug -j $(nproc)

    - name: Create configs
      run: |
        cd configuration_examples/generator

        python3 bottleneck.py \
        --senders 30 \
        --receivers 1 \
        --simulation-time 1000000 \
        --packets 2000 \
        --topology incast_30_to_1_topology.yml \
        --simulation incast_30_to_1_simulation.yml

        python3 bottleneck.py \
        --senders 100 \
        --receivers 2 \
        --simulation-time 1000000 \
        --packets 2000 \
        --topology incast_100_to_2_topology.yml \
        --simulation incast_100_to_2_simulation.yml

        python3 bottleneck.py \
        --senders 1000 \
        --receivers 5 \
        --simulation-time 1000000 \
        --packets 2000 \
        --topology incast_1000_to_5_topology.yml \
        --simulation incast_1000_to_5_simulation.yml

    - name: Run simulations
      run: |
        for config in \
            "configuration_examples/simulation_examples/incast_30_to_1_simulation.yml" \
            "configuration_examples/simulation_examples/incast_100_to_2_simulation.yml" \
            "configuration_examples/simulation_examples/incast_1000_to_5_simulation.yml"
        do
            echo "Running simulation with ${config##*/}"
            time ./build/simulator --config "$config" --no-logs --no-plots
            echo ""
        done
