name: Load testing

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  EXECUTABLE_NAME: nons

jobs:
  load_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake for building project
      run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PROJECT=ON -DBUILD_TESTS=OFF

    - name: Build project
      run: cmake --build build  -j $(nproc)

    - name: Run simulations
      run: | 
        python3 scripts/run_incast_simulation.py --senders 300 --receivers 5 --time 100000000 --packets 20000
        python3 scripts/run_incast_simulation.py --senders 1000 --receivers 10 --time 100000000 --packets 20000
        python3 scripts/run_incast_simulation.py --senders 1000 --receivers 30 --time 100000000 --packets 20000

  profiling_load_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Configure CMake for profiling
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_PROJECT=ON -DBUILD_TESTS=OFF -DPROFILING=ON

    - name: Build project with profiling
      run: cmake --build build  -j $(nproc)

    - name: Run simulations with profiling
      run: | 
        python3 scripts/run_incast_simulation.py --senders 300 --receivers 5 --time 100000000 --packets 20000
        gprof build/${{env.EXECUTABLE_NAME}} > profile.txt
        head profile.txt
        
        python3 scripts/run_incast_simulation.py --senders 1000 --receivers 10 --time 100000000 --packets 20000
        gprof build/${{env.EXECUTABLE_NAME}} > profile.txt
        head profile.txt
        
        python3 scripts/run_incast_simulation.py --senders 1000 --receivers 30 --time 100000000 --packets 20000  
        gprof build/${{env.EXECUTABLE_NAME}} > profile.txt
        head profile.txt
