name: Update root index.html

on:
  push:
    branches:
      gh-pages

jobs:
  rewrite-root-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout to gh-pages
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Remove redundant files
        run: python3 .scripts/delete-useless-files.py
        continue-on-error: true

      - name: Generate new index.html
        run: python3 .scripts/generate-root-html.py index.html

      - name: Configure Git
        run: |
          git config --local user.name "Your Name"
          git config --local user.email "your-email@example.com"

      - name: Commit changes
        run: |
          git add -u
          git commit -m "Add changes from GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
