name: Update root index.html

on:
  workflow_run:
    workflows: ["Build and run project"]
    types:
      - completed

jobs:
  run_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Generate new index.html
        run: 
          SCRIPT_DIR="temp-dir"
          python3 .scripts/generate-root-html.py ${SCRIPT_DIR}
    
      - name: Deploy new index.html GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${SCRIPT_DIR}
          keep_files: true