name: Update root index.html

on:
  workflow_dispatch:

  workflow_run:
    workflows: [Build and run project]
    types:
      - completed

env:
  PUBLISH_DIR: temp-dir

jobs:
  rewrite-root-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout to gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Generate new index.html
        run: 
          python3 .scripts/generate-root-html.py ${{env.PUBLISH_DIR}}
    
      - name: Deploy new index.html GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.PUBLISH_DIR}}
          keep_files: true